# Generated by Django 5.0.14 on 2026-08-28 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingest', '0001_initial'),
        ('ops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('namespace', models.CharField(max_length=80)),
                ('definition', models.TextField(blank=True)),
                ('signals', models.JSONField(blank=True, default=list)),
                ('confidence', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['namespace', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('normalized_name', models.CharField(max_length=255)),
                ('entity_type', models.CharField(choices=[('person', 'Person'), ('org', 'Organization'), ('product', 'Product'), ('model', 'Model'), ('tech', 'Technology'), ('event', 'Event'), ('other', 'Other')], max_length=20)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('summary', models.TextField(blank=True)),
                ('confidence', models.FloatField(default=1.0)),
                ('mention_count', models.PositiveIntegerField(default=0)),
                ('first_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-mention_count', 'normalized_name'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snippet', models.TextField()),
                ('prompt_key', models.CharField(max_length=100)),
                ('prompt_version', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Linkage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicate', models.CharField(max_length=80)),
                ('confidence', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='concept',
            constraint=models.UniqueConstraint(fields=('namespace', 'name'), name='uniq_concept_ns_name'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['entity_type'], name='wiki_entity_entity__d36029_idx'),
        ),
        migrations.AddConstraint(
            model_name='entity',
            constraint=models.UniqueConstraint(fields=('normalized_name', 'entity_type'), name='uniq_entity_norm_type'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='concept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='wiki.concept'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='wiki.entity'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='extraction_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='ops.extractionrun'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='raw_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='ingest.rawarticle'),
        ),
        migrations.AddField(
            model_name='linkage',
            name='object_concept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linkages', to='wiki.concept'),
        ),
        migrations.AddField(
            model_name='linkage',
            name='object_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_linkages', to='wiki.entity'),
        ),
        migrations.AddField(
            model_name='linkage',
            name='subject_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_linkages', to='wiki.entity'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='linkage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='wiki.linkage'),
        ),
        migrations.AddConstraint(
            model_name='linkage',
            constraint=models.CheckConstraint(check=models.Q(('object_entity__isnull', False), ('object_concept__isnull', False), _connector='OR'), name='linkage_object_required'),
        ),
        migrations.AddConstraint(
            model_name='linkage',
            constraint=models.UniqueConstraint(fields=('subject_entity', 'predicate', 'object_entity', 'object_concept'), name='uniq_linkage_triple'),
        ),
        migrations.AddConstraint(
            model_name='evidence',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('concept__isnull', True), ('entity__isnull', False), ('linkage__isnull', True)), models.Q(('concept__isnull', False), ('entity__isnull', True), ('linkage__isnull', True)), models.Q(('concept__isnull', True), ('entity__isnull', True), ('linkage__isnull', False)), _connector='OR'), name='evidence_single_target'),
        ),
    ]
