# Generated by Django 5.0.14 on 2026-08-28 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RssSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField(unique=True)),
                ('site_url', models.URLField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RawArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=1000)),
                ('content', models.TextField()),
                ('summary', models.TextField(blank=True)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('publish_time', models.DateTimeField(blank=True, null=True)),
                ('content_hash', models.CharField(max_length=64, unique=True)),
                ('lang', models.CharField(blank=True, max_length=10)),
                ('extract_status', models.CharField(choices=[('pending', 'Pending'), ('extracted', 'Extracted'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='ingest.rsssource')),
            ],
            options={
                'ordering': ['-publish_time', '-fetched_at'],
                'indexes': [models.Index(fields=['extract_status'], name='ingest_rawa_extract_9073eb_idx'), models.Index(fields=['-publish_time'], name='ingest_rawa_publish_96cf27_idx')],
            },
        ),
    ]
