# Generated by Django 5.0.14 on 2026-08-28 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(max_length=32, unique=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='running', max_length=20)),
                ('trigger', models.CharField(choices=[('cron', 'Cron'), ('manual', 'Manual'), ('seed', 'Seed')], default='cron', max_length=20)),
                ('step_metrics', models.JSONField(default=dict)),
                ('prompt_versions', models.JSONField(default=dict)),
                ('articles_in', models.PositiveIntegerField(default=0)),
                ('entities_saved', models.PositiveIntegerField(default=0)),
                ('concepts_saved', models.PositiveIntegerField(default=0)),
                ('linkages_saved', models.PositiveIntegerField(default=0)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('cost_cny', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('elapsed_ms', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
