"""Quality gates on the committed demo fixture.

`backend/fixtures/demo.json` is what a visitor sees within a second of the page
loading, and it is generated by a model — so it gets checked like any other
untrusted input, in CI, every time.

These read the JSON directly rather than loading it into the database: the file
is the artifact that ships, and a check that only holds after Django has parsed
it would miss a file that is malformed, mis-encoded, or carrying a secret.

`tests/common/test_commands.py` covers the other half — that it still loads.
"""

import json
import re
from collections import Counter, defaultdict
from pathlib import Path

import pytest

FIXTURE = Path(__file__).resolve().parents[1] / "fixtures" / "demo.json"

# PRD section 3 / ROADMAP D7. A graph below these numbers looks like a demo that
# did not work rather than one that did.
MIN_ARTICLES = 80
MIN_ENTITIES = 60
MIN_LINKAGES = 80
MIN_BRIEF_DAYS = 7

# Evidence is verified by substring match at extraction time, and a snippet that
# fails is kept with reduced confidence rather than dropped (PROMPTS.md, the
# 校验规则 table). So a few misses are expected and by design; a lot of them
# would mean the model is paraphrasing instead of quoting, which is the failure
# this project exists to prevent.
MIN_VERBATIM_EVIDENCE_RATIO = 0.90


def _squash(text: str) -> str:
    """Whitespace-insensitive form, matching how the validator compares."""
    return "".join(text.split())


@pytest.fixture(scope="module")
def records() -> list[dict]:
    assert FIXTURE.exists(), f"{FIXTURE} is missing — the public demo ships from this file"
    # Explicit encoding: `dumpdata --output` writes in the locale encoding, and a
    # fixture built on a Chinese Windows box once landed here as GBK.
    return json.loads(FIXTURE.read_text(encoding="utf-8"))


@pytest.fixture(scope="module")
def by_model(records) -> dict[str, dict[int, dict]]:
    grouped: dict[str, dict[int, dict]] = defaultdict(dict)
    for record in records:
        grouped[record["model"]][record["pk"]] = record["fields"]
    return grouped


# --- size ---------------------------------------------------------------


def test_the_fixture_is_valid_utf8_json(records):
    assert isinstance(records, list)
    assert records, "the fixture is empty"


def test_there_is_enough_material_to_browse(by_model):
    assert len(by_model["ingest.rawarticle"]) >= MIN_ARTICLES
    assert len(by_model["wiki.entity"]) >= MIN_ENTITIES
    assert len(by_model["wiki.linkage"]) >= MIN_LINKAGES
    assert len(by_model["wiki.concept"]) >= 1
    assert len(by_model["brief.dailybrief"]) >= MIN_BRIEF_DAYS


def test_the_brief_archive_covers_distinct_days(by_model):
    days = {fields["date"] for fields in by_model["brief.dailybrief"].values()}

    # One brief per day: the date column is unique, but a fixture built from a
    # single day of feeds would still satisfy the count above.
    assert len(days) >= MIN_BRIEF_DAYS


def test_the_graph_is_connected_enough_to_be_worth_drawing(by_model):
    linkages = by_model["wiki.linkage"].values()
    subjects = {fields["subject_entity"] for fields in linkages}

    # A star graph around one entity is not a knowledge graph.
    assert len(subjects) >= 20
    assert len({fields["predicate"] for fields in linkages}) >= 5


# --- referential integrity ----------------------------------------------


def test_every_linkage_points_at_something_in_the_fixture(by_model):
    entities = by_model["wiki.entity"]
    concepts = by_model["wiki.concept"]

    for pk, fields in by_model["wiki.linkage"].items():
        assert fields["subject_entity"] in entities, f"linkage {pk} has a dangling subject"
        target = fields["object_entity"] or fields["object_concept"]
        assert target is not None, f"linkage {pk} has no object"
        pool = entities if fields["object_entity"] else concepts
        assert target in pool, f"linkage {pk} has a dangling object"


def test_every_evidence_row_has_exactly_one_target(by_model):
    for pk, fields in by_model["wiki.evidence"].items():
        targets = [fields["entity"], fields["concept"], fields["linkage"]]
        assert sum(target is not None for target in targets) == 1, f"evidence {pk} is mis-attached"


def test_every_evidence_row_cites_an_article_in_the_fixture(by_model):
    articles = by_model["ingest.rawarticle"]

    for pk, fields in by_model["wiki.evidence"].items():
        assert fields["raw_article"] in articles, f"evidence {pk} cites a missing article"
        assert fields["prompt_key"].startswith("wiki."), f"evidence {pk} has no prompt key"
        assert fields["prompt_version"] >= 1


def test_every_brief_cites_articles_that_exist_with_their_real_urls(by_model):
    articles = by_model["ingest.rawarticle"]

    for pk, fields in by_model["brief.dailybrief"].items():
        citations = fields["citations"]
        assert citations, f"brief {pk} cites nothing"
        for citation in citations:
            article = articles.get(citation["raw_article_id"])
            assert article is not None, f"brief {pk} cites a missing article"
            # The citation is built by the backend from the row, never from the
            # model's own output. If these ever disagree, that rule has broken.
            assert citation["url"] == article["url"]
            assert citation["title"] == article["title"]


def test_the_briefs_reference_markers_all_resolve(by_model):
    for pk, fields in by_model["brief.dailybrief"].items():
        available = {citation["index"] for citation in fields["citations"]}
        cited = {int(marker) for marker in re.findall(r"\[(\d+)\]", fields["content_md"])}

        # A dangling [7] in the prose renders as a link to nowhere.
        assert cited <= available, f"brief {pk} has markers {cited - available} with no citation"


# --- the product promise -------------------------------------------------


def test_evidence_snippets_are_quoted_from_the_articles_they_cite(by_model):
    """The claim the whole site makes, checked against the shipped data."""
    articles = {pk: _squash(fields["content"]) for pk, fields in by_model["ingest.rawarticle"].items()}
    evidence = by_model["wiki.evidence"]
    assert evidence, "no evidence in the fixture"

    verbatim = sum(
        1 for fields in evidence.values() if _squash(fields["snippet"]) in articles[fields["raw_article"]]
    )
    ratio = verbatim / len(evidence)

    assert ratio >= MIN_VERBATIM_EVIDENCE_RATIO, (
        f"only {verbatim}/{len(evidence)} evidence snippets ({ratio:.0%}) are verbatim in their "
        f"source article; the model is paraphrasing instead of quoting"
    )


def test_no_evidence_snippet_is_empty_or_absurdly_long(by_model):
    for pk, fields in by_model["wiki.evidence"].items():
        snippet = fields["snippet"].strip()
        assert snippet, f"evidence {pk} has an empty snippet"
        # ARCHITECTURE 3.2 caps the column at 500.
        assert len(fields["snippet"]) <= 500, f"evidence {pk} exceeds the documented snippet limit"


def test_every_entity_is_backed_by_at_least_one_quote(by_model):
    """An entity with no evidence is an assertion the site cannot support."""
    cited = Counter(
        fields["entity"] for fields in by_model["wiki.evidence"].values() if fields["entity"] is not None
    )
    unsupported = set(by_model["wiki.entity"]) - set(cited)

    assert not unsupported, f"{len(unsupported)} entity/entities have no evidence: {sorted(unsupported)[:5]}"


def test_entity_names_look_like_names(by_model):
    for pk, fields in by_model["wiki.entity"].items():
        name = fields["name"]
        assert name.strip() == name and name, f"entity {pk} has a padded or empty name"
        # A "name" that is really a sentence means the extraction prompt drifted.
        assert len(name) <= 120, f"entity {pk} name looks like prose: {name[:60]!r}"
        assert fields["normalized_name"] == " ".join(name.lower().split())


def test_articles_kept_their_source_urls(by_model):
    for pk, fields in by_model["ingest.rawarticle"].items():
        assert fields["url"].startswith("http"), f"article {pk} has no usable source link"
        assert fields["content"].strip(), f"article {pk} has no body to quote from"


def test_every_shipped_article_was_actually_extracted(by_model):
    """A sweep brings back more than the extraction covers; only the covered ones ship.

    An article with no entities and no evidence would pad the list with a row
    that has nothing to show and no way to reach the rest of the site.
    """
    statuses = {fields["extract_status"] for fields in by_model["ingest.rawarticle"].values()}

    assert statuses == {"extracted"}, f"the fixture carries un-extracted articles: {statuses}"


def test_every_article_is_quoted_by_at_least_one_piece_of_evidence(by_model):
    cited = {fields["raw_article"] for fields in by_model["wiki.evidence"].values()}
    orphans = set(by_model["ingest.rawarticle"]) - cited

    # A handful is fine — a batch can legitimately find nothing quotable in one
    # article — but a large tail means articles are shipping for no reason.
    assert len(orphans) <= len(by_model["ingest.rawarticle"]) * 0.15, (
        f"{len(orphans)} article(s) contribute nothing to the wiki"
    )


# --- nothing that should not ship ---------------------------------------

SECRET_PATTERNS = [
    (r"(?i)\b(api[_-]?key|secret[_-]?key|password|passwd|token)\b\s*[:=]\s*\S{12,}", "credential assignment"),
    (r"\bsk-[A-Za-z0-9]{16,}\b", "OpenAI-style key"),
    (r"(?i)\bbearer\s+[A-Za-z0-9._-]{20,}", "bearer token"),
    (r"\b[0-9a-f]{32}\.[A-Za-z0-9_-]{10,}", "GLM-style key"),
]

# Only checked against links, not against article bodies. A fetched Hacker News
# post whose README says `http://localhost:8000` is quoted third-party text, not
# a leak of the machine that built the fixture — but a *link* to a local address
# would be a demo that is broken the moment it is deployed.
LOCAL_ADDRESS = re.compile(
    r"(?i)//(localhost|127\.0\.0\.1|0\.0\.0\.0|10\.\d+\.\d+\.\d+"
    r"|192\.168\.\d+\.\d+|172\.(1[6-9]|2\d|3[01])\.\d+\.\d+)"
)


@pytest.mark.parametrize(("pattern", "label"), SECRET_PATTERNS, ids=[label for _, label in SECRET_PATTERNS])
def test_the_fixture_carries_no_secrets(pattern, label):
    """This file is public. `scripts/check-clean.sh` scans it too; this is the CI half."""
    text = FIXTURE.read_text(encoding="utf-8")
    hits = re.findall(pattern, text)

    assert not hits, f"{label} found in the fixture: {hits[:3]}"


def test_no_link_in_the_fixture_points_at_a_local_address(by_model, records):
    links = []
    for fields in by_model["ingest.rawarticle"].values():
        links.append(fields["url"])
    for fields in by_model["ingest.rsssource"].values():
        links += [fields["url"], fields["site_url"]]
    for fields in by_model["brief.dailybrief"].values():
        links += [citation["url"] for citation in fields["citations"]]

    offenders = [link for link in links if LOCAL_ADDRESS.search(link or "")]

    assert not offenders, f"links to a local address would 404 in production: {offenders[:3]}"


def test_the_fixture_carries_no_prompt_templates(by_model):
    # They come from a data migration; shipping them twice is how a fixture
    # silently reverts a newer prompt.
    assert not [model for model in by_model if model.startswith("prompts.")]


def test_the_fixture_carries_no_users_or_sessions(by_model):
    for model in by_model:
        assert not model.startswith(("auth.", "sessions.", "admin.", "contenttypes.")), (
            f"{model} does not belong in a demo fixture"
        )
