# Generated by Django 5.0.14 on 2026-08-28 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyBrief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('title', models.CharField(max_length=300)),
                ('content_md', models.TextField()),
                ('citations', models.JSONField(default=list)),
                ('model_name', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('extraction_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='briefs', to='ops.extractionrun')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
